---
    - name: Copy SNMP Config File
      copy:
        src: snmpd.conf
        dest: /etc/snmp/snmpd.conf
        owner: root
        group: root
        mode: '0644'

    - name: Restart SNMPD
      service: name=snmpd state=restarted