---
    - name: Create directory
      file:
        path: /root/{{ item }}
        state: directory
      loop: [ 'vitrine-apache', 'intranet-nginx']

    - name: Copy Dockerfile
      copy:
        src: "{{ item }}"
        dest: /root/
        owner: root
        group: root
        mode: '0644'
      loop: [ 'vitrine-apache', 'intranet-nginx']

    - name: Build vitrine Docker Image
      command: docker build -t {{ item }} /root/{{ item }}/
      loop: [ 'vitrine-apache', 'intranet-nginx']