---
    - name: Deploy vitrine-apache 
      docker_container:
        name: vitrine-apache
        image: vitrine-apache
        container_default_behavior: no_defaults
        state: started
        ports:
        - "80:80"
        tty: true
        detach: true

    - name: Deploy intranet-nginx 
      docker_container:
        name: intranet-nginx
        image: intranet-nginx
        container_default_behavior: no_defaults
        state: started
        ports:
        - "8080:80"
        tty: true
        detach: true