---
    - name: Install Animus's web servers
      hosts: WEB
      remote_user: root
    
      roles:
        - install-docker
        - configure-docker
        - pull-base-image
        - build-image
        - run-container